version: '3.8'

services:
  hopmetrics:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    
  # Optional: Add a scheduled scraper service
  scraper:
    build: .
    command: python scraper.py
    volumes:
      - ./data:/app/data
    depends_on:
      - hopmetrics
    restart: "no"
    profiles:
      - scraper